# This group provides cluster-wide edit access on the redhat-ai-dev team OpenShift cluster.
# This does *not* create your user on the cluster, you **must** have an internal SSO account to log on
kind: Group
apiVersion: user.openshift.io/v1
metadata:
  name: redhat-ai-dev-users
users:
  - bwilcock
  - jdubrick
  - mfaisal
  - yangcao
  - mvaldron
  - tpetkos
  - gmontero
  - jrichter
  - karthik
  - eyuen
  - tkral
  - ktsao
  - uonyeani
  - alizardo
  - tguittet
